// @ts-check
import "@/app/assets/styles/globals.css";
import Pro from "@/components/Providers";
import { Inter } from "next/font/google";
import React from "react";

/** @type {import("next").Metadata} */
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const InterFont = Inter({
	subsets: ["latin"],
});

/** @param {{ children: React.ReactNode; }} args */
export default function RootLayout({ children }) {
	return (
		<html lang="en" translate="no" className="dark">
			<body className={`${InterFont.className} ${InterFont.style}`} suppressHydrationWarning={true}>
				<Pro>
					<div className="flex w-full h-full min-h-full">
						<div className="relative flex w-full h-full flex-col">
							{children}
						</div>
					</div>
					<div className="pointer-events-none bg-white dark:bg-black fixed bottom-0 left-0 h-28 [mask-image:linear-gradient(transparent,#000000)] w-full" />
				</Pro>
			</body>
		</html>
	);
}
